version: "3.7"

services:

  uwsgi:
    build: ./app
    container_name: fltest_uwsgi
    volumes:
      - ./app:/var/www/
    ports:
      - "3031:3031"
    tty: true
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    container_name: fltest_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"