version: "3.7"

services:
  flask:
    build: .
    ports:
      - 5000:5000
    container_name: fltest_web
    volumes:
      - ./src:/code
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000